/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MD2HEPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = { theme: "dark" };
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var CSS_DARK = `
* { margin:0;padding:0;box-sizing:border-box; }
body { background:#0d1117;color:#c9d1d9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;padding:28px 32px;max-width:1100px;margin:0 auto;line-height:1.75;font-size:15px;transition:background .2s,color .2s; }
body.light { background:#ffffff;color:#1f2328; }
body.light h1 { color:#0969da; } body.light h2 { color:#bd561d;border-bottom-color:#d0d7de; } body.light h3 { color:#8250df; }
body.light p { color:#1f2328; } body.light strong { color:#1f2328; } body.light em { color:#1f2328; }
body.light code { background:#e8ecf0;color:#1f2328; }
body.light pre { background:#f6f8fa;border-color:#d0d7de; } body.light pre code { color:#1f2328; }
body.light table { box-shadow:0 1px 3px rgba(0,0,0,.05); }
body.light th { background:#f6f8fa;color:#656d76; }
body.light td { border-bottom-color:#d0d7de; } body.light tr:nth-child(even) td { background:#fafbfc; }
body.light tr:hover td { background:#f0f2f5; }
body.light blockquote { background:#f6f8fa;color:#656d76;border-left-color:#0969da; }
body.light hr { border-top-color:#d0d7de; }
body.light .theme-toggle { background:#e8ecf0;border-color:#d0d7de;color:#1f2328; }
body.light .theme-toggle:hover { background:#d0d7de; }
body.light .subtitle { color:#656d76; }

.theme-toggle { position:fixed;top:14px;right:14px;z-index:999;background:#21262d;border:1px solid #30363d;color:#c9d1d9;padding:5px 14px;border-radius:6px;cursor:pointer;font-size:12px;font-family:inherit;transition:background .2s;user-select:none; }
.theme-toggle:hover { background:#30363d; }

h1 { color:#58a6ff;font-size:32px;margin:40px 0 4px;letter-spacing:-.5px;font-weight:700; }
h2 { color:#f0883e;font-size:22px;margin:36px 0 14px;border-bottom:2px solid #30363d;padding-bottom:10px;font-weight:600; }
h3 { color:#d2a8ff;font-size:18px;margin:28px 0 10px;font-weight:600; }
h4 { color:#8b949e;font-size:13px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:.8px;font-weight:600; }

p { margin:10px 0;line-height:1.75; }
a { color:#58a6ff;text-decoration:none;border-bottom:1px solid transparent;transition:border .2s; }
a:hover { border-bottom-color:#58a6ff;text-decoration:none; }
strong { color:#f0f6fc;font-weight:700; }
em { color:#e6edf3;font-style:italic; }
del,s { text-decoration:line-through;color:#8b949e; }

code { background:#21262d;padding:2px 8px;border-radius:4px;font-size:.875em;font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,monospace; }
pre { background:#161b22;border:1px solid #30363d;border-radius:8px;padding:20px;overflow-x:auto;margin:16px 0;line-height:1.6;font-size:13px; }
pre code { background:none;padding:0;border-radius:0;font-size:inherit; }

table { width:100%;border-collapse:collapse;margin:16px 0;font-size:14px;border:1px solid #30363d;border-radius:8px;overflow:hidden; }
thead { border-bottom:2px solid #30363d; }
th { background:#161b22;color:#8b949e;padding:10px 14px;text-align:left;font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.6px; }
td { padding:10px 14px;border-bottom:1px solid #21262d;vertical-align:top; }
tr:last-child td { border-bottom:none; }
tr:nth-child(even) td { background:#181d24; }
tr:hover td { background:#1c2128; }

ul,ol { margin:8px 0;padding-left:28px; }
li { margin:6px 0;line-height:1.7; }
li::marker { color:#8b949e; }

blockquote { border-left:4px solid #58a6ff;padding:12px 22px;margin:16px 0;color:#8b949e;background:#161b22;border-radius:0 8px 8px 0;font-size:14px;line-height:1.7; }
blockquote p { margin:6px 0; }
blockquote strong { color:#c9d1d9; }

img { max-width:100%;border-radius:8px;margin:16px 0;border:1px solid #30363d; }
hr { border:none;border-top:1px solid #30363d;margin:32px 0; }

.subtitle { color:#8b949e;font-size:13px;margin-bottom:28px;padding-bottom:16px;border-bottom:1px solid #21262d; }

@media (max-width:768px) { body { padding:16px 18px; } table { font-size:13px; } th,td { padding:8px 10px; } }
@media print { body { background:#fff!important;color:#222!important; } .theme-toggle { display:none; } th { background:#f5f5f5!important;color:#555!important; } }
`;
function stripFrontmatter(lines) {
  if (lines.length > 0 && lines[0].trim() === "---") {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        return lines.slice(i + 1);
      }
    }
  }
  return lines;
}
function mdToHtml(md) {
  let lines = md.split("\n");
  lines = stripFrontmatter(lines);
  const html = [];
  let inCode = false, codeLang = "", codeContent = [];
  let inTableHeader = true;
  let inList = [];
  let listType = "";
  let tableOpen = false;
  function flushList() {
    if (inList.length) {
      html.push("<" + listType + ">" + inList.join("") + "</" + listType + ">");
      inList = [];
      listType = "";
    }
  }
  function flushTable() {
    if (tableOpen) {
      html.push("</tbody></table>");
      tableOpen = false;
    }
  }
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (inCode) {
      if (line.startsWith("```")) {
        html.push("<pre><code" + (codeLang ? ' class="language-' + escapeHtml(codeLang) + '"' : "") + ">" + escapeHtml(codeContent.join("\n")) + "</code></pre>");
        inCode = false;
        codeLang = "";
        codeContent = [];
        continue;
      }
      codeContent.push(line);
      continue;
    }
    if (line.startsWith("```")) {
      inCode = true;
      codeLang = line.slice(3).trim();
      codeContent = [];
      continue;
    }
    if (line.startsWith("|") && line.endsWith("|")) {
      flushList();
      const cells = line.split("|").filter((c) => c.trim());
      if (cells.length && cells.every((c) => /^[-:]+$/.test(c.trim()))) {
        inTableHeader = false;
        continue;
      }
      if (!tableOpen) {
        html.push("<table>");
        tableOpen = true;
        inTableHeader = true;
      }
      const tag = inTableHeader ? "th" : "td";
      if (inTableHeader) {
        html.push("<thead><tr>" + cells.map((c) => "<th>" + parseInline(c.trim()) + "</th>").join("") + "</tr></thead><tbody>");
        inTableHeader = false;
      } else {
        html.push("<tr>" + cells.map((c) => "<td>" + parseInline(c.trim()) + "</td>").join("") + "</tr>");
      }
      continue;
    }
    if (line.trim() === "---" && tableOpen) {
      flushTable();
      continue;
    }
    flushTable();
    if (line.startsWith("# ")) {
      flushList();
      html.push("<h1>" + parseInline(line.slice(2).trim()) + "</h1>");
      continue;
    }
    if (line.startsWith("## ")) {
      flushList();
      html.push("<h2>" + parseInline(line.slice(3).trim()) + "</h2>");
      continue;
    }
    if (line.startsWith("### ")) {
      flushList();
      html.push("<h3>" + parseInline(line.slice(4).trim()) + "</h3>");
      continue;
    }
    if (line.startsWith("#### ")) {
      flushList();
      html.push("<h4>" + parseInline(line.slice(5).trim()) + "</h4>");
      continue;
    }
    if (line.startsWith("- ") || line.startsWith("* ")) {
      if (listType !== "ul") {
        flushList();
        listType = "ul";
      }
      inList.push("<li>" + parseInline(line.slice(2).trim()) + "</li>");
      continue;
    }
    if (/^\d+\.\s/.test(line)) {
      if (listType !== "ol") {
        flushList();
        listType = "ol";
      }
      inList.push("<li>" + parseInline(line.replace(/^\d+\.\s*/, "").trim()) + "</li>");
      continue;
    }
    if (inList.length && (!line.trim() || line.startsWith("#"))) {
      flushList();
    }
    if (line.startsWith("> ")) {
      flushList();
      html.push("<blockquote>" + parseInline(line.slice(2).trim()) + "</blockquote>");
      continue;
    }
    if (line.trim() === "---" || line.trim() === "***" || line.trim() === "___") {
      flushList();
      html.push("<hr>");
      continue;
    }
    if (line.trim() === "") {
      continue;
    }
    const trimmed = line.trim();
    if (/^\d+[%\$].*/.test(trimmed) || /^-?\$?\d+(\.\d+)?[%MBT]?[xX]/.test(trimmed)) {
      html.push("<p><strong>" + parseInline(line) + "</strong></p>");
    } else {
      html.push("<p>" + parseInline(line) + "</p>");
    }
  }
  flushList();
  flushTable();
  if (inCode)
    html.push("<pre><code>" + escapeHtml(codeContent.join("\n")) + "</code></pre>");
  return html.join("\n");
}
function parseInline(text) {
  let s = escapeHtml(text);
  s = s.replace(/`([^`]+)`/g, "<code>$1</code>");
  s = s.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  s = s.replace(/__(.+?)__/g, "<strong>$1</strong>");
  s = s.replace(/\*(.+?)\*/g, "<em>$1</em>");
  s = s.replace(/_(.+?)_/g, "<em>$1</em>");
  s = s.replace(/~~(.+?)~~/g, "<del>$1</del>");
  s = s.replace(/!\[(.+?)\]\((.+?)\)/g, '<img alt="$1" src="$2">');
  s = s.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_m, page, alias) => '<a href="' + escapeHtml(page) + '">' + escapeHtml(alias || page) + "</a>");
  s = s.replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>');
  return s;
}
function buildHtml(title, bodyHtml, theme) {
  const css = CSS_DARK;
  const now = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  return '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>' + escapeHtml(title) + "</title>\n<style>\n" + css + "\n</style>\n</head>\n<body" + (theme === "light" ? ' class="light"' : "") + `>
<button class="theme-toggle" onclick="document.body.classList.toggle('light')">\u2601 Switch Theme</button>
<div class="subtitle">` + now + " &middot; Generated by MD to HTML Effectiveness</div>\n" + bodyHtml + "\n</body>\n</html>";
}
async function convertFile(app, file, theme) {
  const content = await app.vault.read(file);
  const htmlContent = mdToHtml(content);
  const outPath = file.parent ? file.parent.path + "/" + file.basename + ".html" : file.basename + ".html";
  if (app.vault.getFileByPath(outPath)) {
    new import_obsidian.Notice("HTML file already exists: " + outPath);
    return;
  }
  await app.vault.create(outPath, buildHtml(file.basename, htmlContent, theme));
  new import_obsidian.Notice("Converted: " + outPath);
}
var MD2HEPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "convert-md-to-html",
      name: "Convert current note to HTML Effectiveness",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking)
            void convertFile(this.app, file, this.settings.theme);
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "convert-batch-md-to-html",
      name: "Convert all markdown in folder to HTML",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("Open a file in the folder to convert");
          return;
        }
        const folder = file.parent;
        if (!folder) {
          new import_obsidian.Notice("Cannot determine folder");
          return;
        }
        const mdFiles = folder.children.filter((c) => c instanceof import_obsidian.TFile && c.extension === "md");
        let count = 0;
        for (const f of mdFiles) {
          const outPath = folder.path + "/" + f.basename + ".html";
          if (this.app.vault.getFileByPath(outPath))
            continue;
          await convertFile(this.app, f, this.settings.theme);
          count++;
        }
        new import_obsidian.Notice("Converted " + count + " files in " + folder.name);
      }
    });
    this.addSettingTab(new MD2HESettingTab(this.app, this));
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data && typeof data === "object") {
      const o = data;
      if (o.theme === "light")
        this.settings.theme = "light";
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var MD2HESettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Display").setHeading();
    new import_obsidian.Setting(containerEl).setName("Output theme").setDesc("Color theme for generated HTML").addDropdown((d) => d.addOption("dark", "Dark").addOption("light", "Light").setValue(this.plugin.settings.theme).onChange(async (v) => {
      this.plugin.settings.theme = v;
      await this.plugin.saveSettings();
    }));
  }
};
