#!/usr/bin/env node
/**
 * Generate RSA keys for the PRD DocuSign app via CDP browser automation.
 *
 * PREREQ: A Chrome tab on apps.docusign.com (production), already on or navigable
 *         to the app edit page for the PRD app.
 *
 * This script:
 *   1. Reads new_app_info.json (created by create_prd_app.js) for the IK
 *   2. Navigates to the app edit page (https://apps.docusign.com/console/apps-and-keys/{IK})
 *   3. Scrolls to the RSA / Authentication section
 *   4. Clicks "Generate RSA"
 *   5. Waits for the key pair to appear
 *   6. Captures private + public keys from the textarea/pre element
 *   7. Saves them to PRD/docusign_private_prd.pem and PRD/docusign_public_prd.pem
 *   8. Saves the Integration Key info for finalize step
 *
 * The keys are GENERATED BY DOCUSIGN (not locally). DocuSign creates them and
 * displays them once in the UI. We capture them immediately.
 */

const CDP = require('/home/wang/wk/code/docusign-keys/PRD/node_modules/chrome-remote-interface');
const fs = require('fs');
const path = require('path');
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

const PRD_DIR = path.resolve(__dirname, '..');

async function getIntegrationKey() {
  // Try new_app_info.json first, then fall back to KEYS.md or prompt
  const infoPath = path.join(PRD_DIR, 'new_app_info.json');
  if (fs.existsSync(infoPath)) {
    const info = JSON.parse(fs.readFileSync(infoPath, 'utf-8'));
    console.log('  Using IK from new_app_info.json:', info.integrationKey);
    return info.integrationKey;
  }
  // Fallback: try current .env
  const envPath = path.join(PRD_DIR, '.env');
  if (fs.existsSync(envPath)) {
    const env = fs.readFileSync(envPath, 'utf-8');
    const match = env.match(/DOCUSIGN_INTEGRATION_KEY="?([^"\n]+)"?/);
    if (match) {
      console.log('  Using IK from .env:', match[1]);
      return match[1];
    }
  }
  console.error('Cannot determine Integration Key. Create PRD/new_app_info.json or set in .env');
  process.exit(1);
}

(async () => {
  const integrationKey = await getIntegrationKey();

  const targets = await CDP.List();
  const target = targets.find(t =>
    t.type === 'page' && t.url.includes('apps.docusign.com')
  );
  if (!target) {
    console.error('No apps.docusign.com tab found. Run login_prd.js first.');
    process.exit(1);
  }
  console.log('Tab:', target.url);

  const attached = await CDP({ target });
  const { Page, Runtime } = attached;
  await Page.enable();
  await Runtime.enable();

  // Step 1: Navigate to the app edit page
  const editUrl = `https://apps.docusign.com/console/apps-and-keys/${integrationKey}`;
  console.log('[1] Navigating to app edit page...');
  console.log('  URL:', editUrl);
  await Page.navigate({ url: editUrl });
  await sleep(8000);

  // Wait for the page to load
  for (let i = 0; i < 20; i++) {
    const hasAuth = await Runtime.evaluate({
      expression: `document.body.innerText.includes('Authentication') || document.body.innerText.includes('Service Integration')`,
      returnByValue: true,
    });
    if (hasAuth.result.value) break;
    await sleep(2000);
  }
  await sleep(3000);

  let curUrl = await Runtime.evaluate({ expression: 'window.location.href', returnByValue: true });
  console.log('  URL:', curUrl.result.value);

  const ss1 = await Page.captureScreenshot({ format: 'png' });
  fs.writeFileSync('/tmp/prd-edit-page.png', Buffer.from(ss1.data, 'base64'));
  console.log('  Screenshot: /tmp/prd-edit-page.png');

  // Step 2: Check if this is the edit page or list page
  const isEditPage = (curUrl.result.value || '').includes(`/apps-and-keys/${integrationKey}`);

  if (!isEditPage) {
    console.log('[2] Not on edit page. Attempting to navigate directly...');
    await Page.navigate({ url: editUrl });
    await sleep(10000);

    curUrl = await Runtime.evaluate({ expression: 'window.location.href', returnByValue: true });
    console.log('  After retry URL:', curUrl.result.value);

    if (!(curUrl.result.value || '').includes(`/apps-and-keys/${integrationKey}`)) {
      console.error('Could not navigate to edit page. Trying Actions > Edit from list...');

      // Click Actions on our app row
      await Runtime.evaluate({
        expression: `
          (() => {
            const rows = document.querySelectorAll('tr, [role="row"]');
            for (const row of rows) {
              if (row.textContent.includes('${integrationKey}') || row.textContent.includes('easy-hire-prd')) {
                const buttons = Array.from(row.querySelectorAll('button, a, [role="button"]'));
                for (const b of buttons) {
                  if (/^actions$/i.test((b.textContent || '').trim())) { b.click(); return true; }
                }
              }
            }
            return false;
          })();
        `,
        returnByValue: true,
      });
      await sleep(1500);

      // Click Edit from dropdown
      await Runtime.evaluate({
        expression: `
          (() => {
            const items = Array.from(document.querySelectorAll('li, button, a, [role="menuitem"]'));
            for (const i of items) {
              if (/^edit$/i.test((i.textContent || '').trim())) { i.click(); return true; }
            }
            return false;
          })();
        `,
        returnByValue: true,
      });
      await sleep(10000);

      curUrl = await Runtime.evaluate({ expression: 'window.location.href', returnByValue: true });
      console.log('  After Edit click URL:', curUrl.result.value);
    }
  } else {
    console.log('[2] Already on edit page.');
  }

  // Step 3: Scroll to find the RSA / Authentication section
  console.log('[3] Scrolling to Authentication / RSA section...');

  // First, check if we're on v2 (old) or v3 (new) UI
  const pageTitle = await Runtime.evaluate({
    expression: `document.title || ''`,
    returnByValue: true,
  });
  console.log('  Page title:', pageTitle.result.value);

  // Scroll to RSA section
  const scrollRes = await Runtime.evaluate({
    expression: `
      (() => {
        // Look for RSA-related headers/sections
        const headings = Array.from(document.querySelectorAll('h2, h3, h4, div[class*="section"], div[class*="auth"], fieldset, legend'));
        for (const h of headings) {
          const txt = (h.textContent || '').toLowerCase();
          if ((txt.includes('auth') || txt.includes('rsa') || txt.includes('service integration') || txt.includes('key')) && txt.length < 80) {
            h.scrollIntoView({block: 'center'});
            return { found: true, text: h.textContent.trim() };
          }
        }
        // Fallback: scroll down in steps
        window.scrollTo(0, 1200);
        return { found: false, scrollY: 1200 };
      })();
    `,
    returnByValue: true,
  });
  console.log('  Scroll:', JSON.stringify(scrollRes.result.value));
  await sleep(2000);

  // Step 4: Check if there's a "Generate RSA" button
  console.log('[4] Looking for Generate RSA button...');
  const rsaBtnRes = await Runtime.evaluate({
    expression: `
      (() => {
        const btns = Array.from(document.querySelectorAll('button, a, [role="button"]'))
          .filter(b => b.offsetParent);
        const rsaBtns = btns.filter(b => /generate rsa/i.test((b.textContent || '').trim()));
        const allBtns = btns.map(b => (b.textContent || '').trim()).filter(t => t && t.length < 40);
        return {
          rsaButtons: rsaBtns.map(b => b.textContent.trim()),
          allVisible: allBtns.slice(0, 25),
        };
      })();
    `,
    returnByValue: true,
  });
  console.log('  RSA buttons:', JSON.stringify(rsaBtnRes.result.value, null, 2));

  // Check if the old (v2) UI is shown — look for file upload style
  const v2Check = await Runtime.evaluate({
    expression: `
      (() => {
        // v2 UI has file inputs and radio buttons for integration type
        const fileInputs = document.querySelectorAll('input[type="file"]');
        const radioLabels = Array.from(document.querySelectorAll('label'))
          .filter(l => /integration key|secret key|private|public/i.test(l.textContent || ''));
        return {
          hasFileInputs: fileInputs.length > 0,
          radioLabels: radioLabels.map(l => l.textContent.trim()),
        };
      })();
    `,
    returnByValue: true,
  });
  console.log('  UI check:', JSON.stringify(v2Check.result.value));

  // Step 5: Click Generate RSA or handle v2 UI
  let keysCaptured = false;
  let capturedPrivate = '';
  let capturedPublic = '';

  if (rsaBtnRes.result.value.rsaButtons.length > 0) {
    // v3 UI — click Generate RSA button
    console.log('[5] v3 UI detected. Clicking Generate RSA...');
    await Runtime.evaluate({
      expression: `
        (() => {
          const btns = Array.from(document.querySelectorAll('button, a, [role="button"]'));
          for (const b of btns) {
            if (b.offsetParent && /generate rsa/i.test((b.textContent || '').trim())) {
              b.scrollIntoView({block: 'center'});
              b.click();
              return b.textContent.trim();
            }
          }
        })();
      `,
      returnByValue: true,
    });
    await sleep(8000);

    // Check for confirm dialog
    const confirmRes = await Runtime.evaluate({
      expression: `
        (() => {
          const btns = Array.from(document.querySelectorAll('button'))
            .filter(b => b.offsetParent && /^(confirm|yes|generate|ok)$/i.test((b.textContent || '').trim()));
          if (btns.length > 0) {
            btns[0].click();
            return { clicked: true, text: btns[0].textContent.trim() };
          }
          return { clicked: false };
        })();
      `,
      returnByValue: true,
    });
    if (confirmRes.result.value && confirmRes.result.value.clicked) {
      console.log('  Confirmed:', confirmRes.result.value.text);
      await sleep(6000);
    }

    // Look for keys in textareas/pre/code elements
    const keysRes = await Runtime.evaluate({
      expression: `
        (() => {
          const tas = Array.from(document.querySelectorAll('textarea, pre, code, [class*="key" i]'));
          let pub = '', priv = '';
          for (const t of tas) {
            const txt = (t.textContent || t.value || '').trim();
            if (txt.startsWith('-----BEGIN PUBLIC KEY-----')) pub = txt;
            if (txt.startsWith('-----BEGIN RSA PRIVATE KEY-----') || txt.startsWith('-----BEGIN PRIVATE KEY-----')) priv = txt;
          }
          return { pubLen: pub.length, privLen: priv.length, count: tas.length };
        })();
      `,
      returnByValue: true,
    });
    console.log('  Keys found:', JSON.stringify(keysRes.result.value));

    if (keysRes.result.value.privLen > 0) {
      // Fetch full keys
      const fullRes = await Runtime.evaluate({
        expression: `
          (() => {
            const tas = Array.from(document.querySelectorAll('textarea, pre, code, [class*="key" i]'));
            let pub = '', priv = '';
            for (const t of tas) {
              const txt = (t.textContent || t.value || '').trim();
              if (txt.startsWith('-----BEGIN PUBLIC KEY-----')) pub = txt;
              if (txt.startsWith('-----BEGIN RSA PRIVATE KEY-----') || txt.startsWith('-----BEGIN PRIVATE KEY-----')) priv = txt;
            }
            return { pub, priv };
          })();
        `,
        returnByValue: true,
      });
      capturedPrivate = fullRes.result.value.priv;
      capturedPublic = fullRes.result.value.pub;
      keysCaptured = true;
    }
  } else if (v2Check.result.value.hasFileInputs) {
    // v2 UI — upload public key file
    console.log('[5] v2 UI detected (file upload). Looking for upload controls...');
    // Look for "Add RSA Keypair" button
    const addRsaRes = await Runtime.evaluate({
      expression: `
        (() => {
          const btns = Array.from(document.querySelectorAll('button, a, [role="button"], label'))
            .filter(b => b.offsetParent);
          const addBtn = btns.find(b => /rsa|public key|keypair|add.*key|upload.*key/i.test(b.textContent || ''));
          return addBtn ? { found: true, text: addBtn.textContent.trim() } : { found: false };
        })();
      `,
      returnByValue: true,
    });
    console.log('  Upload control:', JSON.stringify(addRsaRes.result.value));
  }

  if (keysCaptured && capturedPrivate && capturedPublic) {
    // Save keys to PRD directory
    const privPath = path.join(PRD_DIR, 'docusign_private_prd.pem');
    const pubPath = path.join(PRD_DIR, 'docusign_public_prd.pem');
    fs.writeFileSync(privPath, capturedPrivate);
    fs.writeFileSync(pubPath, capturedPublic);
    console.log(`\n[✓] RSA keys saved:`);
    console.log(`  Private: ${privPath}`);
    console.log(`  Public:  ${pubPath}`);
  } else {
    console.log('\n[!] Could not capture RSA keys from the page.');
    console.log('  The UI may require a different approach. Check screenshots:');
    console.log('  /tmp/prd-edit-page.png');

    // Take final screenshot for debugging
    const ss2 = await Page.captureScreenshot({ format: 'png' });
    fs.writeFileSync('/tmp/prd-rsa-failed.png', Buffer.from(ss2.data, 'base64'));
    console.log('  /tmp/prd-rsa-failed.png');

    // Save what we managed to capture
    if (capturedPrivate || capturedPublic) {
      console.log('  Partial keys captured — saving anyway...');
      if (capturedPrivate) {
        fs.writeFileSync(path.join(PRD_DIR, 'docusign_private_prd.pem'), capturedPrivate);
      }
      if (capturedPublic) {
        fs.writeFileSync(path.join(PRD_DIR, 'docusign_public_prd.pem'), capturedPublic);
      }
    }
  }

  // Save IK for finalize step
  const state = {
    integrationKey: integrationKey,
    appName: 'easy-hire-prd',
    userId: 'cce9485b-58dd-41d3-9f47-a7969a012fae',
    accountId: '694285719',
    keysCaptured: keysCaptured,
    privateKeyPath: 'PRD/docusign_private_prd.pem',
    publicKeyPath: 'PRD/docusign_public_prd.pem',
    timestamp: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(PRD_DIR, 'rsa_setup_state.json'), JSON.stringify(state, null, 2));
  console.log('Saved: PRD/rsa_setup_state.json');

  await attached.close();
  process.exit(0);
})().catch(e => { console.error(e.message); console.error(e.stack); process.exit(1); });
